import { Encounter, EncounterParams } from '../encounters.js';
import { Location } from '../locations.js';
import { randomFrom, roll } from '../random.js';

type DynamicString = string | (() => string);

interface PrismeerEncounterParams extends EncounterParams {
  dmNote?: DynamicString;
}

class PrismeerEncounter extends Encounter {
  dmNote?: string | (() => string);

  constructor(params: PrismeerEncounterParams) {
    super(params);
    this.dmNote = params.dmNote;
  }

  async show(location: Location) {
    const note = typeof this.dmNote === 'function' ? this.dmNote() : this.dmNote;
    if (note) {
      console.log(this.dmNote);
    }
    await super.show(location);
  }
}

function randomPartyMember(): string {
  return randomFrom(['Eaton', 'Harrow', 'John', 'Nacho', 'Rhiannon', 'Throne']);
}

const rawText: Array<DynamicString | [DynamicString, DynamicString]> = [
  // From https://spinewrinkle.com/d30-random-fey-encounters/
  () => `${roll(8)} talking hedgehogs ask for help in finding their magic bone whistle.`,
  `A solitary willow sister can be seen dancing around her willow tree, attempting to revive it. The tree is covered in a bright red fungus, and looks to be heavily infected. The willow sister pleads with the party for aid.`,
  `You see pixies tying all the flowers in a garden into bows. This kills the flowers.`,
  `You come to a bridge over a creek in the middle of a field. On both sides of the bridge sits a small wooden bucket, inside each of which is a collection of metal trinkets: nails, pins, thimbles, coins, etc.`, // Trying to cross the bridge without depositing a similar item brings the wrath of the troll living beneath the bridge.
  [`You meet an elf traveling merchant selling common items at incredibly cheap prices.`, `All the merchants' items are cursed in a mildly frustrating way.`],
  [`A fox is caught in a hunter's trap.`, `The fox will grant a boon to anyone who aids it, or subsequently curse anyone who attempts to take advantage of it.`],
  [`Six deformed pookas invite passers-by to take part in their tea and crumpets party.`, `They expect impeccable manners, but do not explain their standards and customs.`],
  [`You see a small stone ruin sitting in the middle of a large lily pond.`, () => `${roll(3)} redcaps have taken up residence within.`],
  [`You find a saddled horse wandering around riderless. It is beautiful and friendly.`, `Attempting to ride the horse rapidly causes it to become ferociously ill-tempered, running into a nearby lake where it transforms into a strangling mass of seaweed and tries to drown the would-be rider.`],
  [`A small, cozy hut occupied by a hideous old woman who agrees to lodging for travelers if they will help her chop some firewood and muck her goats' pen.`, `When chores are attempted, the firewood is so hard it breaks the axe, and no matter how much manure shoveled, there is always more.`],
  [() => `${roll(6)} crooning selkies lure travelers to their ocean grotto, where they will tempt the travelers to stay and mate with them in exchange for ${roll(100) + roll(100) + roll(100)} pearls.`, `The selkies fail to mention that the mating takes place beneath the waves.`],
  `You come across an abandoned fire pit. On the spit is a half-eaten pig roast. A confusing mess of tracks around the site show massive hoofprints the size of a man's head, and occasional drops of blood amidst the tangle of sleeping blankets and ripped bags. The tracks disappear thirty feet from the roast.`,
  [`You spy a cave entrance littered with small animal bones.`, `Within is a sick ogre maid drinking bonebroth soup. She will ask for captured animals for her soup as she cannot hunt with her illness.`],
  // `The path traveled upon is discovered to be a closed circle. Pixies have been stealing from you as you walk endless around their grove.`
  [`A circle of cats speaking in the language of men can be heard in the next clearing.`, `Upon noticing the listeners, the cats suddenly go quiet and stalk them through the following days.`],
  `Two goblin craftsmen in leather aprons argue over the ownership of a silver hammer. They demand you help arbitrate.`,
  // A field of carnivorous flowers. Save vs falling asleep for d4 hours.
  [`As you walk into the clearing a translucent leprechaun with an over-sized pouch ducks behind a rock.`, `Searching the area finds a shallow grave, covered in stones, of a dead leprechaun and his empty pot of gold. In his fist is a note, written by him, leading to his murderers. He knew.`],
  [`You kick a small pebble and suddenly a faerie dog to appears. He introduces himself as Yordrew and claims to have been imprisoned in the pebble for 100 years and is now free thanks to you, and swears to repay the debt no matter what it takes.`, `The faerie dog forgets about it the next day and wanders off when no one is looking.`],
  // Each night for the last week, someone in the local village has spoken of hearing a far-off melancholy scream. The next day, that person has been found dead. The village is in a panic.
  [() => `The shadow of a dog begins trailing ${randomPartyMember()}. No one else can see it.`, `If they attempt to kick or attack the shadow somehow, the shadow disperses to the sound of rueful whining.`],
  // `Farmer Conanson has noticed that if he leaves a saucer of milk out, his floors are swept and clothes stitched together when he wakes up. However, he's found he's had to leave more and more milk out or instead his clothes are rent and gouges left on his wall. He's starting to run out of milk.`
  // During the night, a hobgoblin attempts to rob someone, and escapes by climbing a tree. If captured, indignantly claims to be “Puck, the consort of the king of faeries.”
  () => `${roll(2) + 1} bog sprites sleep peacefully in a circle beneath a cypress tree. Between them is a burlap sack filled with gold and silver jewelry.`,
  [`A talking crow offers to guide travelers through a vine-tangled forest in exchange for "a shiny bauble."`, () => `If taken up on the offer, it will lead them safely through the woods. If refused, the travelers will become lost in the forest for ${roll(4) + roll(4)} days with all their food stolen after their first night's sleep.`],
  [`A small, black-haired girl leads nine marching puppets. Each puppet plays a wind or percussion instrument.`, `If party is spotted, the puppets flee in nine directions and the girl turns into a tree.`],
  `A hunter lies wounded with multiple piercing wounds. Two giant white stags watch from the distance.`,
  [`A small human hand with gold rings on each finger is found in the center of a fairy ring.`, `If someone attempts to move it, the hand grips the would-be mover and that person must save or become small mushroom.`],
  [() => `A swarm of ladybugs surrounds ${randomPartyMember()}.`, `If they are swatted away, nothing happens. If the person accepts, they are granted a vision of a powerful magical weapon, guarded by a giant, only a day's travel away.`],

  // From https://www.dndspeak.com/2022/08/30/100-feywild-encounters/
  `A rain cloud begins to follow you as you travel.`,
  `A talking owl appears before you and offers to guide you through a vine-tangled forest in exchange for "a shiny bauble."`,
  [`The trees are major gossips. As you walk through them Eaton is sure he can hear the whispers in the rustling of the leaves.`, `If you tell the trees a juicy secret that no-one else knows they will open the path to wherever you wish to go. The trees will rustle outwardly from the tree you told the secret too as it tells the other trees next to it.`],
  `A bloody pile of corpses lay ahead of you. After approaching them they sit up, dispel the illusions, and the assorted fey all run off laughing.`,
  // [`A fey fighting exhibition.`, `Many of the fey, when slain in the fey realms, simply appear once more alive some time after, be it a few hours or days later (unless executed by the Fey courts, or special preparations taken by the combatants to ensure death) -- as such, fighting exhibitions can quickly become bloody, brutal affairs, but with little lasting consequence to the participants. It is also not uncommon for fey fighters to pull forth concealed weaponry, and it being totally within the rules of the ring to do so. Mortals participating in these fights do not have such protection as almost-guaranteed resurrection.`],
  `You encounter a stretch of rocky terrain which proves very difficult to walk through. The stretch ends abruptly at a sheer cliff, over the edge of which there appears to be a grassy forest growing out sideways. Looking back, you suddenly realize you've been walking up a sheer cliff.`,
  // `Fey prisoners cruelly collared with cold-iron, toiling as slaves in the Fey Queen's vineyards of Celestial grapes (the only such fields remaining since the sinking of Atlantis).`
  [`A giant caterpillar offers a toke from their bubble pipe.`, `Creatures that imbibe, and are not firmly attached to the ground, begin to float away.`],
  // `The Feywild is mutable and ever changing, and the Queen's Palace is no exception. While the party is traversing the Feywild, they come across a Museum Gallery Wing juxtaposed with the other normal terrain nearby. Subtle owl motifs emerge, (and aside from the nearly perfect weather and lighting conditions) the only clues to the change are that statues and artworks appear out of the ground as if inextricably part of the natural landscape. This particular wing is a bit overgrown, and guarded by 1d3+1 Guardian Portrait from Curse of Strahd and 1d4 Animated Armor. For a higher level encounter, add a Stone Cursed from Mordenkainen's Tome of Foes, a Clay Gladiator from Tomb of Annihilation, or a Caryatid Column from 3e Fiend Folio. Despite the overgrown nature, mere mortals shall never gaze upon the works of art and beauty the Queen holds dear, making trespassing here very dangerous.`,
  [`An innocent woodchuck stands and stares at you while eating from a vegetable garden.`, `The local witch finally catches them in the act and punishes the woodchuck with a curse.`],
  [`You stumble upon a group of fey having a tea party with a random assortment of forest creatures. There are several seats open and they gleefully invite you over to enjoy some drinks and snacks.`, `It may or not be a friendly encounter.`],
  // `A funeral hosted by the Seelie court that is gathering before a mighty parade. All who pass by are magically charmed into following the procession, and seemingly throw themselves into re-enacting (sometimes violently) scenes from the life and times of the deceased.
  [() => `${roll(4) + roll(4)} fairies are following behind you. Whenever you look behind or seem to be getting wise they hide.`, `They're quite oblivious however, and if snuck up on can be heard making bets about which party member will get eaten by the beast ahead/get the most lost in the forest/follow the wisps etc.`],
  // `An owlbear in a fine hat, and vest with a golden pocket watch. The owlbear is friendly, but has a smoking problem and is addicted to halfling tobacco. It does not appear to be a threat, except on moonless nights, when it grows 4 times as large and becomes an unstoppable rage-filled killer.`,
  `A chipmunk playfully hops on a field of large mushrooms that have a natural bounce to them. One of the larger mushrooms gets irritated and tries to teach this chipmunk a lesson in not pestering others.`,
  [() => `A crossroads where all signs point to ${randomFrom(['"Downfall"', '"Loomlurch"', '"Motherhorn"'])} in different directions.`, `(where the players have most recently departed from). Any locals (when asked for directions) will announce: "Oh, you can't get there from here, I'm afraid, you'll have to go backwards, you see.. sometimes going backwards is the only way to move forwards, my grandpapa would always say.."`],
  [`You come across a tin automaton in a copse of hazel trees, wielding an ax and a flute made from a metal jug and a funnel. The automaton playing the flute causes the copse of hazel to quickly grow into the shape of large, fine, living cages, which the automaton uses the ax to cut down.`, `Careful observation of the automaton's chest might reveal dried blood, opening the chest reveals a beating heart. Once a month, when the moon is full, the automaton is driven to kill, in order to replace the heart.`],
  `A veritable mountainous bower of house sized flower petals covers the ground, forming a pile literally the size of a small mountain, and reeking of lovely perfume fragrance. At the center of the pile, seemingly placed lovingly, is the corpse of a gargantuan bumblebee mount, with fine saddle and tackle, barding, etc. sized for a humanoid or possibly even a large creature to ride. It is covered in "giant" (small sized) fire-ants, literally ants that burn with flame, and surrounded by towering tree-sized poles of smoking incense. It is difficult to tell if the ants are devouring the corpse, or guarding it; perhaps it is both.`,
  // `A city-state sized hive of giant, anthropomorphic bees, living inside the festering corpse of an even larger gargantuan lion. Their honey is claimed to be much prized by the Unseelie queen.`,
  // `A large river blocks the path. A dryad nearby has a boat, but it's taken root and she's struggling to convince it to go back out onto the water. A loud snap and the sudden disappearance of a moose that was drinking on the other bank prove swimming a dangerous course of action.`,
  `A flock of half-sized miniature black kenku, a too tall fey with several extra joints, and a clockwork wagon piled high with fine trade goods. The kenku are skilled crafters, and on the wagon are portable workshops of many kinds, including a miniature blacksmith forge, a wind-up loom, potter's wheel, kiln, and apothecary. The skinny fey is dressed as an undertaker, all in black, their lips and eyes have been sewn closed, and their long fingers end in sewing needles a foot long. They have a set of extra joints in between each joint a normal humanoid possesses, and appear to be double-jointed, at that. The fey offers tailoring of outfits, and sells everything from silken robes woven by spiders, to transparent gowns made of only large dragonfly wings.`,
  // `A lovely orchestra made up of fey creatures. They carry traditional musical instruments, such as the violin or the flute. They all are very posh and elegant, and inform you that they are going to see the fairy queen. If the party asks to hear the music, they put on a performance. The twist, all music is very loud, sweary, and is rock music.`,
  // `A night-sky so beautiful you get drunk, literally, taking it all in.`,
  [`A group of friendly boggles are about to start a game with water balloons, and invite you to participate.`, `Participants mustn't leave a magically marked area of the forest, and the winner is the last person standing who hasn't been hit by a balloon. Bogles can and will use their special ability to warp around the place at opportune times.`],
  `You encounter a foreign fey noble carried around on a palanquin, except the bearers are all on ridiculously tall stilts.`,
  [`You come across a coven of seven platinum haired and silver skinned automaton sisters with carved gems for eyes, serene expressions, fine features, and silk-lined robes of samite and ermine. The sisters sit atop white horses, but do not speak, instead the horses speak for them, asking the way to Mithrendain.`, `If the horses are offered whiskey, they will happily reveal that they are from the moon and on a diplomatic envoy mission.`],
  // `Loud music and vocal commotion is heard underneath a thick range of a colorful forest. A vegetable, honey, or herb conference/con is seen with many booths and dressed up forest creatures and fey perusing the countless goods, experts, and trinkets as they revel in fandom and nerdiness.`,
  `As you pass through a swarm of dragonflies a sprite approaches and angrily accuses you of interrupting their parade. They demand recompense in the form of one good deed, freely given.`,
  [`There is a rectangular hole in the ground surrounded by cut stone. There is no visible water and the inner walls are dark with ash. A small child's head pops out from inside and asks if you are there to deliver their presents.`, `If they don't throw down a present the child's head will start to climb the chimney and is revealed to be a creature who steals faces.`],
  // `The mutable nature of the feywild extends to other Arch Fey's Palatial Estates as well. While the party is traversing the Feywild, they come across a wing of an Arch Fey's palace resembling a Greco-Romantic Boudoir juxtaposed (but also elegantly entwined) with the other normal terrain nearby. A copse of dryads in humanoid form are Ladies in Waiting for the Arch Fey, the players suddenly find them in a compromised position, and much embarrassment is had by all. The players must not be caught by the Arch-fey's Guards, however, or the fun will end. 1d6+1 Blink Dogs and 1d2+1 Yeth Hounds from Volo's Guide to Monsters hunt the party through the halls and gardens, along with a Forlarren (from Mordenkainen’s Fiendish Folio Volume I) and 1d4 Twigjacks converted from Pathfinder Bestiary 2. All the pursuing searchers wear the Arch Fey's Livery, and aim to kill half of the party, and capture, interrogate, and then torture the rest to death.`,
  `An impassable river in a deep and dangerous gorge with a single bridge guarded by a peerless warrior who threatens to throw off the bridge any who cross without first speaking absolute truth. Traffic is quite backed up.`,
  [`You come across a circular stream, roughly 100 feet in diameter, crossed by two footbridges.`, () => `Going under either of the bridges leads to another identical stream somewhere else. The stream goes through ${roll(4)} such portals before returning to the original circle.`],
  `A majestic imperial stag fully 50 hands tall, bearing a rack of antlers with at least 24 points. The stag wears a collar with a gold sigil of Titania. It escorts a harem of at least twenty does, of similar size, and a herd of much smaller "normal" sized hart and hind trail behind. The ground beneath the majestic creatures seems to grow more verdant, lush, and covered in fresh growth as they traverse it.`,
  `A headless knight has been wandering the area, feeling around for his head.`,
  [`A column of small hedgehogs in knightly accoutrement riding upon roosters as mounts`, `The Order of the Night Quill, literally small awakened hedgehogs. The Knights are fighting a much larger and more powerful enemy, pretending to not need any assistance, despite contrary evidence.`],
  `A wildly drunk satyr sits atop a fallen log hurling insults at passersby, the crude words transform into barbed daggers mid-air.`,
  [`A group of children wearing strange faded masks and eating cake and drinking lemonade.`, `If approached they refuse to share.`],
  // `An hag traveling in a house-wagon, with a celestial angel enslaved and imprisoned. The angel has had their wings removed.`,
  // `The Feywild has its own version of every biome in the Material Plane, and sometimes more than one, and often very very wild. The Feywild Ocean is particularly mercurial, occasionally "deciding" to move inland. Seemingly overnight, the terrain the party is on becomes a very small island in a very large sea. Locals take this in stride, adapting as if it were any other day. This progresses for 1d6 days, before reverting to its former state, leaving the players once more in whatever biome they were in before the ocean moved.`,
  [`A terrified looking person is found balancing a goblet on their head filled to the brim with water. They plead for you to help them. They explain that a fairy put the goblet there and that if a single drop of water falls from the goblet they will die. They have been standing there for quite some time, and are terrified to attempt to remove the goblet.`, `Examination of the water or goblet reveals it is ordinary, and if any of it spills nothing happens. The poor soul has been tricked by mischievous Fey.`],
  // `You come across a large number of fey creatures towing along various mounts (some griffons, a unicorn, etc) who are friendly to the players. If asked what they are doing, they tell the players they are organizing a race, and invite the players to join. Players can either run, use their own mounts (any & all are accepted) or they can rent a mount for a certain amount of gold. In total, about 100 fey creatures compete in the race, and will use underhand tactics to win`,
  [`A school of literally flying fish, blown far inland by a squall.`, `The fish are medium to large sized creatures (use the stats of a shark) and can hunt ground based prey.`],
  // `A forest fire, set by a giant wolf made of ash and flame, in hot pursuit of spectral, god-sized prey, and some say, its long-lost mate. The wolf is accompanied by a large pack of smaller ash-wolves, who tend to attack and surround prey of their own. The creatures can speak, and at least one of them is a Shifter Druid and can be reasoned with, and they venerate the giant ash wolf, following the fires it starts, making hunting easier.`,
  // `You come across a beautiful clearing in the woods that the denizens refer to as 'The Dancing Grove'. A massive tree sits in the middle of the clearing, with musical instruments made of sticks, twigs, and reeds dangling from its branches. Every full moon, the massive tree comes alive and begins playing all of the instruments at once, creating some of the most beautiful music the players have ever heard. Creatures from all around come to the Dancing Grove to hear the enchanting music.`,
  // `A fresh race course has been staked out overnight magically, and Fey well-to-do have gathered. The race involves each owner's horse being carried around the track by the owners' stablehands and servants. At least one will keel over, dead from exhaustion.`,
  [`A convoy of caged humanoid (non-fey) children and fey guards pass by.`, `They are destined to be delivered to one of the Nine Hells every seven years.`],
  [`A group of fey sit around a strangely colored fire telling scary stories and allow you to join.`, `The time comes for your party to share. Be careful what stories you tell, it might come to pass around you.`],
  // `A crossroads encounter with a number of fey threatening what appears to be wealthy humanoids who owe a debt. The fey are very restrained, civil, and polite, but they are a real threat, and are emissaries from a group of fey who perform assassinations for hire in the mortal world, and know of a way to easily transit between the realms, at least reliably enough to kidnap wealthy individuals and threaten them at a fey-crossroad! The fey threats have names like: "Herb Robert" (They are the spokesman, also known as "Death-Comes-Quickly"), "Johnny Jump-up", "Black-eyed Susan", "Jack-in-the-Pulpit", and "Golden Alexander", and each wear a flower matching their name, and in some way reflect the plant they are named for.`,
  `A massive group of satyrs are having a wild party in the woods. The surrounding creatures are getting concerned, because a satyr party can easily spin out of control.`,
  // `The players meet an extremely kind and helpful fey that, unbeknownst to them, has the ability to demand favors in return for any favors they give. The fey will attempt to get characters as much on their debt as they can with food, shelter, hospitality and perhaps even fending off some wild creatures for them, and the favors it asks can't be ignored by the players, as if they were under the effects of a powerful spell. However, the fey limits its requests to silly things that would get you laughed at.`,
  `A Faun is sitting in the ruins of an old manor house with a few sprites near him. He's drawing patterns on the ground with chalk.`,
  // `A mining settlement inside of the corpse of a beyond-gargantuan elemental comprised of once-living gemstone. Multiple levels of glittering gemstone have been carved into spectacular, if grisly cathedrals and vaults. The Queen of the Fey has ordered the mine to move the entire corpse and turn it into a new palace, but it has become infested with gemstone themed spirits that slaughter anyone who disturbs them.`,
  [`You spot a group of animated shrubs that are talking in common, plotting world domination.`, `However, they lack the wits, resources and manpower to pull it off in any conceivable way, and all but the leader can be scared off pretty easily. The leader is likely to hold a grudge if the party messes with the gathering.`],
  [`You encounter a large pond. Any reflection in the pond appears to be aged several decades.`, `(the party will appear older, objects appear to have been weathered. This even applies to the surroundings: trees will appear taller than they are.)`],
  // `A rare species of rabbit that can comprehend most languages. Their unique fur changes color from white to a blue-ish black, matching the phases of the moon, and they also grow in size, starting as normal rabbits on a new moon and eventually growing to large size during a full moon. Greedy hunters might be searching the forest in order to harvest their extremely valuable pelts.`,
  // `A disguised hag invites the party to dinner. The food continuously refills and if they succeed on a DC15 wisdom saving throw they will realize that it continually feels like the start of the meal. Trying to get up will reveal their feet stuck to the legs of the chairs.`,
  // `A village of humanoids with heads that look like those of dogs. Farmers of this village are in an uproar; they are harvesting the fruit of a plant that grows humanoids and is a much sought after delicacy at the tables of both the Seelie and Unseelie courts. A humanoid (in all appearances human) runs up to the party and requests sanctuary, attempting to hide the fact that they have a portion of vine growing from her belly button.`,
  // `The players are struck by an intoxicating sweet smell (may require WIS saving throws). Those affected by its hunger inducing effect are attracted to a leaf covered area. The most perceptive (not affected) players will understand that when stepping on the region they'll fall onto a giant venus flytrap. If no one falls to the trap, the flytrap will act all indignant and flippant that it produced that sweet smell for nothing. That the contract has been made and it wasn't getting its share back. Says it will start raising a vine dome until either one of the PCs sacrifices himself or they toss some sort of food to the trap's cup.`,
  // `Giant land-whales with mouths the size of football fields seemingly made of wood, wicker, and brambles. They appear overnight and are seemingly "beached" miles from any ocean and dying. Inside their mouths and gullets are countless species of rare or extinct sea creatures, many still alive (albeit not for long).`,
  [`A field filled with what appear to be brick ovens of all shapes and sizes. Many are burning or still hot, crewed by a flock of black feathered kenku`, `bandits who favor fire-based attacks. The ovens grow naturally, it seems, but the bandits cut down the queen's forests to fuel them, and seem to spread and grow in number each time a new oven is lit.`],
  [`You find yourselves in a clearing where 6 colorful mushrooms grow`, `equal to the party's size (4 players = 4 mushrooms) are growing. They can't leave the clearing unless they eat the mushrooms. If they try they will walk for a while and inevitably find themselves back on the clearing. GM digression what happens when they eat the shrooms.`],
  // `A warforged is chopping wood near a cottage. Curled up on the steps of the cottage is a lion.`,
  // `Instead of a static town or village, settlements and cities in the Feywild are more like metaphorical boats being swept along a current, the locations of buildings relative to each other change frequently as does their location in the world but they somehow manage to be relatively near each other as needed. However sometimes a building or two will break from the herd and go its own way; one normally close location is now further away, and seemingly doesn't want to be found, and the Players have been tasked with tracking it down and possibly leading it (the instructions are vague) back to the city proper!`,
  `While walking through the forest, an argument can be heard up ahead. Upon investigating, you find two ancient Eladrin engaged in a battle of wits. They are currently arguing about who can tell the longest story, and they want you to judge.`,
  // `A giant mushroom around 200ft tall, that exerts a strange gravity effect, letting players walk up the stem. An old hermit lives in a grotto among the gills.`,
  [`You encounters a colony of house-cats who walk on their hind-legs like people do. Today there is a parade, where they pick the new king. The old king and the new king are both at either ends of the parade on palanquins.`, `They must joust to determine the victor, but first, games of chance, and a civilized feast!`],
  // `Snow begins to fall from a clear sky. As soon as the last bit of ground is covered, all fey creatures begin digging at the snow, which is somehow several inches, or even feet, deep. They begin pulling fruit from beneath the snow, with white skin and purple meat. The fey alternate between gorging themselves with the fruit and using them as projectiles and weapons against others in a joyous frolicking melee. If consumed, the fruit's texture is that of a medium-rare steak and has an alternating flavor that moves from tangerine to pear and back. Eating the fruit grants a feeling of warm youthful days playing with friends by the river. After 10 minutes the snow on the ground clears as though it was never there. Any fruit kept lasts 6d12 hours before disintegrating into sparkling dust with a slight toot and a child's laughter.`,
  `A fine carriage, drawn by deep shadows, and a driver hell bent for leather, stopping at nothing, nearly runs you down before passing out of sight.`, // for fear of their own life, even going so far as to smash through barricades, or attack anyone attempting to stop them. It either runs down the players, or crashes near them...
  // `A queen's finest fighting force of guards, wearing magical bronze armor that looks like the heads of owls, and grants flight, fly by overhead in formation. Local fey cower in fear and try to hide.`,
  // `A school of floating airborne goldfish whose scales are literally gold pieces. Catching and killing the fish causes it to revert to a regular fish. Capturing the fish and selling it alive is worth 10 gp each.`,
  `A small trickling stream about a foot in width is impossible to pass. The flowers nearby tell you the stream is very self-important and wants tribute to allow you to cross. They mimic the river in a silly voice "Give me your silver. Give me your breath. Give me the sounds of your step."`,
  // `The Feywild hosts a twisted fun-house mirror version of every biome on the material plane, and then some. One second the party is in the civilized farm-land portions of the Feywild, and the next in a dazzling colored prismatic desert made of crystals and finest of pure white sand; beset upon by 1d2 Crystalline Trolls guarding a small patch of ordinary wildflowers! (Beneath the wildflowers is a single Perfect Astral Gem worth 2d20x100gp, from which another Troll will spawn in a few years...) Should the party continue on towards where the nearest civilized outpost would have been located in Farmland, they find that the locals treat the changed situation as if it were any other Fwendniday, except everyone's clothing has magically shifted style to match the desert theme...`,
  `A flying boat and crew, filled with a catch of flying fish. The crew are eager to get to market before the fish are spoiled. The captain, "Great-Uncle Penderfish" keeps giving the smolt sweetbreads...`,
  // `Ultraviolet technicolor gnomes wearing bowler hats in gangs, riding giant flying hummingbird mounts, launching air attacks on passersby.`,
  // `A hag offers the party a vial of acid for 20 GP, and demonstrates its destructive capabilities by using her hand as an example (the hand grows back after 1d4 hours). If the party decides to buy it, anything they dissolve with the acid turns into some kind of juice.`,
  // `A lovely park table and set of benches set with a fine and intricately carved set of jeweled game pieces for a strange 13 by 13 square type of chessboard with 46 pieces each. A lifelike statue of a player sits on one bench, with the board in an early-mid game state. Moving a tile triggers the curse. The secret trick is that each side is petrified while it is not their turn, until a winner is chosen. A non-petrified player may leave the game, and unfortunately, until it is finished, the other player may not be unstuck.`,
  // `Eleven, faceless Fey priests celebrating an obscure festival to an extinct eleven-faced deity. The entire fey countryside is gathered around a well set beneath a decrepit statue of the ancient god, with eleven faces in different directions and strange expressions. Surrounding the well in a perfect circle is a copse of Larch with dry, golden leaves, and ten of the faceless priests have tied themselves up inside the branches. The eleventh though, refuses, and is fighting with the crowd.`,
  `You come across a field of giant pumpkins the size of houses. A few of the pumpkins have strange music playing from near or inside them. A fey field-worker struggles to set up an instrument and loudspeaker combination, alternately moving mindlessly, and then humming whatever music matches coming from the giant gourds.`,
  // `A field full of patches of Glimmergrass, tall grass patches of glass-like iridescent plants. A creature within 5 feet of a specific patch of Glimmergrass has the effect of Mirror Image, unless they already have an effect like it active (in which case no additional effect occurs). The effect of anything within the fields is like stepping into a maze full of funhouse mirrors. A hunting party of 1d6+1 goblinoids stalk the fields.`,
  // `A vicious continent-spanning flock of starlings, nightingales, and whippoorwills with razor sharp beaks, claws, and booming calls. Those who hear the birds know to seek shelter quickly. The fools who stay out in such a flight are quickly doomed and likely never seen again!`,
  // `The party arrives at a forest that has come alive. Each of the trees has a soul and talks to the party, and if the party looks at one of the leaves, they will see the veins forming the picture of a little room inside the leaf, and a little leaf dude sitting at his table for afternoon tea.`,
  [() => `${roll(6) + roll(6)} Red-Skinned Satyrs wearing "fake" Devil costumes and wielding mining equipment. they are busy digging into a set of beyond-gargantuan teeth embedded in the ground like one half of a giant mouth. The "devils" seem intent on causing cavities and tooth decay in the giant teeth.`, `At least one is either a Sorcerer or Warlock, or a Forlarren from Mordenkainen's Fiendish Folio Volume I . They are aggressive to anyone who approaches. They have been cursed/charmed to be this way. However, in addition to being cursed and humiliated, they have also been cursed with illusory dental-pain that exactly mirrors the damage they deal to the giant teeth. Those who approach within 60 feet of any afflicted must make a Moderate DC Wisdom save each round or be forced to participate in the cavity causing activity, those who succeed on the save are immune for 1 hour. Additionally, each round, the illusory dental pain may be resisted with a second Moderate DC Wisdom save. Those that succeed on that save are immune to the effect for 1 hour as well. The illusory pain affects Concentration checks as if receiving 3d6 hp worth of damage (but it does not deal actual damage).`],
  `A Fey noble has decided that he doesn't want to be a noble any longer. He recruits you to show him how to be more of a 'commoner'.`,
  [`You come across a man clad in clashing bright colors playing a pipe and leading a parade of rats and children.`, `The Pied Piper, yes, that one... fresh from returning after stealing away the rats and children of Hamelin. The children and rats are both here, and the Piper tries to play dumb. But there are political implications to freeing the children. Namely, without them, the Fey realm is in debt to the Nine Hells. A tithe is paid every seven years in the form of children's souls to remain neutral and uninvaded. Interfering will result in incurring the wrath of the Queens.`],
  // `The mutable nature of the feywild extends to the Queen's Palace as well. While the party is traversing the Feywild, they come across a Royal Wing juxtaposed with the other normal terrain nearby. Beautiful golden screens; priceless, eggshell thin ceramic vases, and polished brass mirrored walls form a sort of whispering gallery, occupied by a Spring Eladrin and an Annis Hag from Mordenkainen's Tome of Foes, along with a number of lesser co-conspirators. They are discussing some sort of curse, assasination, or coup against the Throne. Should they discover the players, they will attempt to capture, then charm the group into obedient thrall.`,
  // `A huge, but strangely erudite ogre with giant warhammer, and in full magical platemail, challenges all who attempt to pass to single combat.`,
  // `A gaggle of twenty-score nobly dressed humanoids, each tied at the waist and wrist to another by a silken cord, wearing woven crowns of marigolds, along with a veritable army of fey servants in fine livery keeping herd, many have several blackbirds perched on their shoulders. The servants keep plying the humanoid nobles with wine, sweet-meats, sweet smelling smoke, and are feeding them lotus blossoms, marigolds, and mushrooms. One of each group of noble's servants is wearing fine brocade robes, has an elaborate and imperious head-dress, and seems most versed in magical enchantments. If questioned, the nobles will claim they are headed to a brothel, urge the party to stay, and offer to cover their tab. If questioned, instead, the fey "in charge" will explain the gaggle are late for a wedding and urge the group to leave them be and stop contributing to the chaos.`,
  // `A noble minotaur herdsman named Sir Cease, leading his herd of ... wait.. are those people? They look like people, but are twice the size, and have thick curly hair on their heads, and they all have beards. They eat grass like cattle and sound like them too, and none are capable of speaking. They'll fetch a fine price, and might even grace the Queen's table, according to the Herdsman.`,
  [`You run into a human that has been cursed by a mischievous fey into thinking they are a cat. This becomes evident when the person does silly things such as wonder out loud how the players can spot them hiding inside a small bush that could never conceal their actual body proportions, or when they attempt and fail to climb trees or walls using their bare hands and feet.`, `If befriended, the person might ask the players to help lift the curse, either by means of a spell or by confronting the fey that cursed them and getting it to remove the curse through some kind of bargain.`],
  // `Was that a rabbit wearing a waistband and looking at a pocket watch that just hopped by?`,
  // `A cult of Prometheans, Fey who see the mortals' mastery of iron in religious terms, and seek to claim it for themselves by adopting as many mortal ways as possible. Their cult is small, scattered, but they firmly believe it is growing.`,
  `Owls. Everywhere you look, there is at least one. Are they following you?`, // Even inside! The Queen Sees All.
  // `A patch of screaming Mandrake; quite valuable, provided one survives their deathly and deafening screaming. A powerful, crazed dryad guards the grove the patch is located in and hates all creatures, seeing them as fit only for fertilizer, and will actively kill any who approach.`,
  // `The Queen's Garden is known to be vast; so vast in fact that no single Gardener knows the true extent or boundary of it! You'll know you're in the Queen's Garden by the Owl Motif subtly hidden in sight. Those who trespass on the Garden are not known for living long and peaceful lives. The problem is, the Garden is secretly growing, and seemingly overpowering the Will of the army of Master Gardeners who tend it. None dare approach the Queen about the issue, and it enveloped the entire Village of West Bollingbrook last week! Find the Villagers, please?`,
  // `An entire traveling shoe-store of enchanted (cursed) dancing shoes. The shoes are animated, and are here to do two things, Look Good, and Kicking Ass.. and they're done looking good. Amongst the 1d4 Swarms of Animated Shoes (use Swarm of Flying Books , but reskin them to be various boots, clogs, sandals, slippers, etc) are a number (a number that is level appropriate for the party) of tougher, Daz's Iron Boots of Retribution; they are each a pair of metal boots that have the Heat Metal ability (Bonus Action, Recharge 4-6; as the spell) against a target they have successfully attacked in melee this round; additionally, until the start of it's next turn, any creature adjacent to or touching the object (for instance, in order to grapple) must beat a Easy-Medium DC Constitution save, or take 1d8 Fire damage. For Daz's Iron Boots stats, use a CR1 Medium Animated Object, and increase AC by +2.`,
  // `A group of goblins are dragging along what looks like a cannon. They're all equipped with iron weapons. If asked they announce that they intend to kill the Queen, and, after devouring her flesh and stealing her power, destroy the lady of pain, Asmodeus, and Vecna. If fought they're strong enough to force the players to retreat.`,
  // `A group of fey are playing free-for-all pretend spell battles, and invite the players to join them. Each participant is given an illusory pool of HP matching their maximum HP and a bunch of random spoof spell scrolls of all sorts of powerful magic that anyone can use (playing cards could be used to symbolize different spells of all levels). As for the rules of the game, the scrolls deal illusory damage, participants who lose all their illusory hit points are taken out of the game, and anyone that deals damage through other means is immediately disqualified.`,
  [`A belch loud enough to be heard by the entire party comes from one of the party's bags. Inside is a portly sprite snoozing atop a half-eaten rations.`, `The sprite has been traveling with the party for a while, eating their food, and fell asleep after a hearty meal. They happily provide information about the area, but despite any efforts to stop the sprite, they somehow manage to always be munching on a morsel of the party's supplies.`],
];

export const encounters = [
  ...rawText.map((entry): PrismeerEncounter => {
    let description: string;
    let dmNote: string | undefined;
    if (Array.isArray(entry)) {
      description = typeof entry[0] === 'function' ? entry[0]() : entry[0];
      dmNote = typeof entry[1] === 'function' ? entry[1]() : entry[1];
    } else if (typeof entry === 'function') {
      description = entry();
    } else {
      description = entry;
    }
    const name = description.substring(0, 20);
    return new PrismeerEncounter({
      name,
      description,
      dmNote,
    });
  }),
];
